PR# Dashboard flats status count change
paixindia/RealEstateCRM pull request #26
Opened 2021-04-08 05:28 UTC by Shivangi-Dixit

- Dashboard flats status real count change
- Added Link to the Detail page
- Loader Added

2021-04-08 06:06 UTC, neersx commented on AdminProject.BusinessLayer.ServiceManager/CRM/ProjectServiceManager.cs
> +            var flats = await _projectRepository.GetAllFlatsAsync();
You need to pass ProjectId so that flats of specific project can be loaded. Else it will show all project flats count.

2021-04-08 06:08 UTC, neersx requested changes
Please check comments and fix

2021-04-10 17:09 UTC, Shivangi-Dixit commented on AdminProject.BusinessLayer.ServiceManager/CRM/ProjectServiceManager.cs
> +            var flats = await _projectRepository.GetAllFlatsAsync();
It is fixed

2021-04-10 17:19 UTC, neersx approved these changes

2021-04-10 17:22 UTC, merged